# Setup

title:            sleepy's site
description:      site of sleepy star.
url: https://sleepystars.github.io
repository: sleepystars/sleepystars.github.io

permalink: pretty

# Configuration
plugins: 
- jekyll-remote-theme

# color scheme
color_scheme: catppuccin

remote_theme: just-the-docs/just-the-docs

# search function
search_enabled: true

# back to top
back_to_top: true
back_to_top_text: "back up please"

#edit ig?
gh_edit_link: false

#footer
footer_content: "idk this isn't copyrighted, theme is just the docs shoutout to them"

#mermaid diagram
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
